# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{any_view}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Daniel Neighman"]
  s.date = %q{2009-12-13}
  s.description = %q{View helpers with an absolute minimum of requirements}
  s.email = %q{has.sox@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "lib/any_view.rb",
     "lib/any_view/asset_tag_helpers.rb",
     "lib/any_view/core_ext/array.rb",
     "lib/any_view/core_ext/hash.rb",
     "lib/any_view/core_ext/string.rb",
     "lib/any_view/form_builder/abstract_form_builder.rb",
     "lib/any_view/form_builder/standard_form_builder.rb",
     "lib/any_view/form_helpers.rb",
     "lib/any_view/format_helpers.rb",
     "lib/any_view/tag_helpers.rb",
     "lib/any_view/tilt_base.rb",
     "test/fixtures/basic_form_for.erb",
     "test/fixtures/builder_type_form_for.erb",
     "test/fixtures/capture_concat.erb",
     "test/fixtures/capture_concat.haml",
     "test/fixtures/content_for.erb",
     "test/fixtures/content_for.haml",
     "test/fixtures/content_tag.erb",
     "test/fixtures/content_tag.haml",
     "test/fixtures/delete_form_for.erb",
     "test/fixtures/field_set_tag.erb",
     "test/fixtures/fields_for.erb",
     "test/fixtures/fields_for.haml",
     "test/fixtures/fields_for_basic.erb",
     "test/fixtures/fields_for_nil.erb",
     "test/fixtures/form_for.erb",
     "test/fixtures/form_for.haml",
     "test/fixtures/form_for_nil.erb",
     "test/fixtures/form_tag.erb",
     "test/fixtures/form_tag.haml",
     "test/fixtures/form_tag_methods.erb",
     "test/fixtures/form_tag_methods.haml",
     "test/fixtures/link_to.erb",
     "test/fixtures/link_to.haml",
     "test/fixtures/mail_to.erb",
     "test/fixtures/mail_to.haml",
     "test/fixtures/multipart.erb",
     "test/fixtures/multipart_form_for.erb",
     "test/fixtures/put_form_for.erb",
     "test/fixtures/standard_form_builder.erb",
     "test/helper.rb",
     "test/test_asset_tag_helpers.rb",
     "test/test_form_builder.rb",
     "test/test_form_helpers.rb",
     "test/test_format_helpers.rb",
     "test/test_tag_helpers.rb"
  ]
  s.homepage = %q{http://github.com/hassox/any_view}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{View helpers designed to work just about anywhere}
  s.test_files = [
    "test/helper.rb",
     "test/test_asset_tag_helpers.rb",
     "test/test_form_builder.rb",
     "test/test_form_helpers.rb",
     "test/test_format_helpers.rb",
     "test/test_tag_helpers.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_development_dependency(%q<haml>, [">= 2.2.1"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rack-test>, [">= 0.5.0"])
      s.add_development_dependency(%q<webrat>, [">= 0.5.1"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 2.2.1"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rack-test>, [">= 0.5.0"])
      s.add_dependency(%q<webrat>, [">= 0.5.1"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 2.2.1"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rack-test>, [">= 0.5.0"])
    s.add_dependency(%q<webrat>, [">= 0.5.1"])
  end
end

